name: Build APK
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install EAS CLI Directly
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm install

      - name: Generate Keystore Automatically
        run: |
          keytool -genkeypair -v -keystore my-release-key.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000 -storepass 123456 -keypass 123456 -dname "CN=Expo Developer, OU=Mobile, O=Expo, L=Cairo, S=Cairo, C=EG"

      - name: Build Android APK
        run: |
          eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
